// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionsButtons: typeof import('./src/app/components/ActionsButtons.vue')['default']
    ChangeVendorLink: typeof import('./src/app/components/ChangeVendorLink.vue')['default']
    ConfirmAccountInformation: typeof import('./src/app/pages/OpenBanking/ConfirmAccountInformation.vue')['default']
    DefaultLayout: typeof import('./src/app/layouts/DefaultLayout.vue')['default']
    DialogueWindow: typeof import('./src/app/components/DialogueWindow.vue')['default']
    EmailDialogueWindow: typeof import('./src/app/components/EmailDialogueWindow.vue')['default']
    FetchingAccountData: typeof import('./src/app/pages/OpenBanking/FetchingAccountData.vue')['default']
    FlowSelection: typeof import('./src/app/pages/CommonFlow/FlowSelection.vue')['default']
    Imprint: typeof import('./src/app/pages/Legal/Imprint.vue')['default']
    InputScaCode: typeof import('./src/app/pages/OpenBanking/InputScaCode.vue')['default']
    Invite: typeof import('./src/app/pages/SignUp/Invite.vue')['default']
    LatestEmail: typeof import('./src/app/components/LatestEmail.vue')['default']
    LegalLayout: typeof import('./src/app/layouts/LegalLayout.vue')['default']
    LoadingCigarette: typeof import('./src/app/components/LoadingCigarette.vue')['default']
    LoadingSpinner: typeof import('./src/app/components/LoadingSpinner.vue')['default']
    LoginAdmin: typeof import('./src/app/pages/Management/LoginAdmin.vue')['default']
    MagicLinkDialogue: typeof import('./src/app/components/MagicLinkDialogue.vue')['default']
    Management: typeof import('./src/app/pages/Management/Management.vue')['default']
    MicroFlowStepOne: typeof import('./src/app/pages/MicroFlow/MicroFlowStepOne.vue')['default']
    MultiVendorSelect: typeof import('./src/app/pages/CommonFlow/MultiVendorSelect.vue')['default']
    OpenBankingSuccessful: typeof import('./src/app/pages/OpenBanking/OpenBankingSuccessful.vue')['default']
    OpenBankingTerms: typeof import('./src/app/components/OpenBankingTerms.vue')['default']
    Overview: typeof import('./src/app/pages/Overview.vue')['default']
    PaginationControls: typeof import('./src/app/components/PaginationControls.vue')['default']
    PrivacyPolicy: typeof import('./src/app/pages/Legal/PrivacyPolicy.vue')['default']
    ProgressBar: typeof import('./src/app/components/ProgressBar.vue')['default']
    ResetAccountDialogue: typeof import('./src/app/components/ResetAccountDialogue.vue')['default']
    ResetButton: typeof import('./src/app/components/ResetButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCountry: typeof import('./src/app/pages/OpenBanking/SelectCountry.vue')['default']
    SelectInstitution: typeof import('./src/app/pages/OpenBanking/SelectInstitution.vue')['default']
    SelectScaMethod: typeof import('./src/app/pages/OpenBanking/SelectScaMethod.vue')['default']
    SessionExpired: typeof import('./src/app/pages/Management/SessionExpired.vue')['default']
    Settings: typeof import('./src/app/components/management/Settings.vue')['default']
    ShowAllButton: typeof import('./src/app/components/ShowAllButton.vue')['default']
    SignUp: typeof import('./src/app/pages/SignUp/SignUp.vue')['default']
    StartEmbeddedFlow: typeof import('./src/app/pages/OpenBanking/StartEmbeddedFlow.vue')['default']
    StartSingleRedirect: typeof import('./src/app/pages/OpenBanking/StartSingleRedirect.vue')['default']
    Team: typeof import('./src/app/components/management/Team.vue')['default']
    TermsForValidation: typeof import('./src/app/pages/Legal/TermsForValidation.vue')['default']
    TermsOfService: typeof import('./src/app/pages/Legal/TermsOfService.vue')['default']
    TransactionDenied: typeof import('./src/app/pages/MicroFlow/TransactionDenied.vue')['default']
    TransactionSuccess: typeof import('./src/app/pages/MicroFlow/TransactionSuccess.vue')['default']
    TransactionValidation: typeof import('./src/app/pages/MicroFlow/TransactionValidation.vue')['default']
    Unauthorized: typeof import('./src/app/pages/CommonFlow/Unauthorized.vue')['default']
    ValidationSuccess: typeof import('./src/app/pages/CommonFlow/ValidationSuccess.vue')['default']
    Verifications: typeof import('./src/app/components/management/Verifications.vue')['default']
  }
}
